/**
 * The Belgian commune register (D-11): every commune since the 1 January 2025
 * mergers, by NIS code, with its French name, its Dutch name where it differs,
 * and its postcodes. The data is `communes.json`, regenerated by
 * `scripts/communes/build.ts`; a professional's zone stores NIS codes only.
 *
 * Pure and small enough (about 36 KB) for the commune picker to search in the
 * browser; stubs 7 and 15 reuse it for requests and search.
 */
import data from "./communes.json";

export type Commune = {
  nis: string;
  fr: string;
  nl?: string;
  postcodes: string[];
};

export const COMMUNES: readonly Commune[] = data as Commune[];

const byNis = new Map(COMMUNES.map((c) => [c.nis, c]));

export function communeByNis(nis: string): Commune | undefined {
  return byNis.get(nis);
}

export function isKnownCommune(nis: string): boolean {
  return byNis.has(nis);
}

/** Lower case, no accents, hyphens and apostrophes as spaces: "Liège" finds "liege". */
export function fold(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[-'’.]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Communes matching what she typed: a postcode (or its first digits), or the
 * start of a word of the French or the Dutch name. Names that start with the
 * query come first, then the rest alphabetically.
 */
export function searchCommunes(query: string, limit = 8): Commune[] {
  const q = fold(query);
  if (!q) return [];

  if (/^\d+$/.test(q)) {
    return COMMUNES.filter((c) => c.postcodes.some((p) => p.startsWith(q))).slice(0, limit);
  }

  const scored: [number, Commune][] = [];
  for (const commune of COMMUNES) {
    const names = [commune.fr, commune.nl].filter(Boolean).map((n) => fold(n!));
    if (names.some((n) => n.startsWith(q))) scored.push([0, commune]);
    else if (names.some((n) => n.split(" ").some((word) => word.startsWith(q)))) {
      scored.push([1, commune]);
    }
  }
  return scored
    .sort((a, b) => a[0] - b[0] || a[1].fr.localeCompare(b[1].fr, "fr"))
    .slice(0, limit)
    .map(([, c]) => c);
}
